import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from '@/components/providers';
import "./globals.css";


const customFont = localFont({
  src: "./font/font.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Crypto Lottery",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={customFont.className}>
      <body
        className={`antialiased`}
        suppressHydrationWarning
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}